# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-25 00:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20160524_1643'),
    ]

    operations = [
        migrations.CreateModel(
            name='UFaculty',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('f_school', models.CharField(max_length=40)),
                ('f_faculty', models.CharField(max_length=40)),
                ('f_major', models.CharField(max_length=40)),
            ],
            options={
                'managed': False,
                'db_table': 'ufaculty',
            },
        ),
    ]
