# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-10 18:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_stuclass'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='stuclass',
            table='stuclass',
        ),
    ]
