# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-18 00:13
from __future__ import unicode_literals

import django.contrib.postgres.fields
from django.db import migrations, models

from core.models import FClass, AuthUser


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20160610_1459'),
    ]

    operations = [
        migrations.CreateModel(
            name='CQuestions',
            fields=[
                ('qid', models.AutoField(primary_key=True, serialize=False)),
                ('classid', models.ForeignKey('FClass', null=False, db_column='classid')),
                ('qstring', models.CharField(max_length=200)),
                ('option', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=200), size=None)),
                ('answers', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=200), size=None)),
            ],
            options={
                'managed': False,
                'db_table': 'cquestions',
            },
        ),
        migrations.CreateModel(
            name='CResults',
            fields=[
                ('rid', models.AutoField(primary_key=True, serialize=False)),
                ('classid', models.ForeignKey('FClass', null=False, db_column='classid')),
                ('username', models.ForeignKey('AuthUser', null=False, db_column='username')),
                ('grade', models.CharField(default='TBD', max_length=10)),
            ],
            options={
                'managed': False,
                'db_table': 'cresults',
            },
        ),
    ]
