# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-19 19:33
from __future__ import unicode_literals

from django.db import migrations, models

from core.models import AuthUser


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_cquestions_cresults'),
    ]

    operations = [
        migrations.CreateModel(
            name='UStudent',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.ForeignKey("AuthUser", null=False, db_column='username')),
                ('s_school', models.CharField(max_length=40)),
                ('s_faculty', models.CharField(max_length=40)),
                ('s_major', models.CharField(max_length=40)),
            ],
            options={
                'managed': False,
                'db_table': 'ustudent',
            },
        ),
    ]
